# DOC: Installing instructions for travis CLI: https://github.com/travis-ci/travis.rb#installation
# DOC: .travis.yml file format: https://docs.travis-ci.com/user/deployment/heroku/
language: ruby
rvm:
  - 2.4.1
services:
  # SOURCE: https://docs.travis-ci.com/user/database-setup/#PostgreSQL
  - postgresql
# DOC: https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle
before_script:
  # SOURCE: http://stackoverflow.com/a/12896545/5764181
  - psql -c 'CREATE USER basimilchdbuser SUPERUSER;' -U postgres
  # SOURCE: https://docs.travis-ci.com/user/database-setup/#Using-PostgreSQL-in-your-Builds
  - psql -c 'CREATE DATABASE basimilchdb_test OWNER basimilchdbuser;' -U postgres
# The 'after_success', 'after_failure', 'after_script' and subsequent stages do
# not affect the the build result.
# DOC: https://docs.travis-ci.com/user/customizing-the-build/#Breaking-the-Build
# To create a tag only if the build succeeded but fail the build if the tagging
# does not work, we have to specify the 'script' step with '&&' as follows.
# DOC: https://docs.travis-ci.com/user/customizing-the-build/#Customizing-the-Build-Step
script:
  - bundle exec rake && ./.travis_tag.sh
sudo: required
before_deploy:
  - ./.travis_before_deploy.sh
after_deploy:
  - ./.travis_after_deploy.sh
# SOURCE: https://github.com/travis-ci/travis-ci/issues/1476#issuecomment-55614399
# DOC: https://docs.travis-ci.com/user/customizing-the-build/#Whitelisting-or-blacklisting-branches
branches:
  only:
    - master
    - dev
#   except:
#     - /^build-[0-9a-z\-]*/

deploy:
  # SOURCE: http://docs.travis-ci.com/user/deployment/heroku/
  provider: heroku
  api_key:
    secure: xaS4YniLEpDrvSRfy4v84Ezj7j2te38mGGIgkusTOxa8KhBahkQiaQQdq5aydbYk+e9vZm+nh7pGGM6k7U8wVx2OYrmWhrknPYsOvWatjzqPh9Ehpct0dIr2lka3W/RIcJVmmXVFKVi3E7fR4FwoaQIOJZFltrhtaxx9g4reCdQy4MYn5Piv5su5XVaLbaitsGr7954fu+/abkrJgcpztBUCox2vq376qnDbmfb7OUUqBVCtMOLVZpH/LV3cjKqPTY9H73dx3Z8lPburMuRKJiQeauaRoZcpAAptATkSNwChmUrpft9zTNRuN98gR2CZqjm3FUIvN57uWLAqaOxhuazIo7x8iA4jn/+gCKKVzmU46kuk0N2cDnwksjR0KdP3zZgRrCp16gg38syHnZVy2pNNprRIPR4tstrC5cFdzhnGs6k0azk0XwndS2kF20pQrJ9FrqQDSvq3RmF5iInL6LIoXVMDYTLWC2se1D9BZVmH/DBKMXjvNGUBx9sVGVbulcWujeUXJ+s4PGJ/BwJrgEdAPlcTUpfWycmDE89GVIDdotUQxte8xxRh+8gyRY/mt6upRN4BK62s55R6axwzOx/B5CcaYZRxBkopxL8K4qF5hUekwsbQDbpbfT6MH7RvrefOq3Kx/AOfq0vcfI3M5pEhCqKSeKEj4vJ6I4iPQU0=
  # SOURCE: http://docs.travis-ci.com/user/deployment/heroku/#Deploy-Strategy
  strategy: git
  app:
    master: basimilch
    dev: basimilch-dev
  run:
    - "bundle exec rake db:migrate"
  on:
    repo: basimilch/basimilch-app
addons:
  postgresql: "9.6"
  code_climate:
    repo_token:
      secure: qC5Z41NwPZz59EvpX5kM+A7r2WTHJzuXTNIloQGTLpP/QI/tOGJgZ8taYxjU/OzjKM9Qi0xXdshjs/oR9PUWptQY6bb4FSFFLGIr2W614kCYoYJrhlrtvcabIUgrXJ2F38rLp1PSfLSnGkAGH+e9qm+IAyGb3kkoLr7NDpqWWTL/r8j7quaBoR2NB62vRNPxUAyl9xdq4OQ8wqGNx9ALDpnGetjdDBzugnoRh/8uXzld0hC+EycpiPrWWgkenmbPVV6JK2EF/G7/fl/tnPzseT8X14oW2y2u4o9QdTMcAgCsHzAka+o8Ty+MYyu7iReeVH1p/6/875gUn7/7yz6Ivum34C/ErgTGNhKXKj3F7yEyrb1mtkttBT/1I463wtZPi/JRBKof7jhP623ZGhYP/6CR0q6gEDT6sspmUekaYAb9covtRS4KDDlzgOOGVWUoS7f7qUetrw9eJz1rNr2Yo3G61sbP8SSMZu5J+2tKk7fESTD/gHHP9CGLrtZgFSmeiyOvyG72brGV57zsH39ozW/zwdkyG3xWLn+R5+bntOn7fj1BzRXoG155I/Ef3jV8Ais+IxjGPkQTlMnhX0kki3hWk2+OiG4HYWiiZwR9KKGX87X4muSximCgBfAd1ZJU6XBnUBXNVQs9Oz/d2A/jhpwWAu9qUal01qKD6GjQz9I=
notifications:
  slack:
    secure: Untt1WvmnTnEHSl/ELsVViyJl+kX2j4QKTh+CpVmKx5W8av+fKgBf0OsXZh8UGJjqMD0UEvOzd0ja4crH4aQOjtZsCIfd2oOstf3QNIfBf7Fzqr6aQBehhC3lTD+r663T8ej9phe2OLwLor5XwDKclgy+5RSMHBvGLs+D6sSsrrxvZ1WOAEzr0ucDdztoCFLaWl8snFcQk/ZEBAi8c0UHxfjEFZK6GaQa/XxvlD7TLM04oZM/vUf8f+HTQISstF1S139gzmYussRLkxKH9iGkit4MTM9haxJvoudkb5S3LBhxqXY6os6czOMaQHLZP5Cr0XjYsJqHVZTzJCRELjO8bXWMCnjC7ylxbNBdJxDQPVW3ECH2Q/zVQXx/RevbBDG/1miUV99gKKE0MVfN3j1Qq220+L6cQCos8z/mUyz27htDOvwz6M3VG8OxL6hxJHvAhWpQN1ZnOQVK4P9PPUg43nuylJKDXcO3DeaGHQiLBmXy9NikGDvyrMys5N1X5jKp2a1URfbsAvSUbvx4Jwk+3fluPIGTplWTyrEO+a5KbtvChNW/cWHJpOf77gZwiFHSxjVsmnbhaDY/laf3L1lqF/Aa8YxycgLUIsN2ClfwRzgzB5rNhkzWbX5pLajnyd2Bc37xLJmIN4Lh0Y1W4y1yaRshdlPhmKDJM9OYExpoHs=

# SOURCE: https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming
dist: trusty
