language: ruby
rvm:
- 2.2.1
deploy:
  # Source: http://docs.travis-ci.com/user/deployment/heroku/
  provider: heroku
  api_key:
    secure: Nsc366gSOexO9Vz08Xw/hiDostVhloakyyG//DcfaoWmP8Hf3dzBl80KqBHlvEfXgD1NTKJ6ttN7yxzJWyV+MROfkoQ4F4Y0bOb65iPlVW4RvrWRWR0C6wlVUeVOOkdLGIp4xsC5n5pNe+UFK/uoTcHsL5ASF/wtTGMTKpXLhW+6HgQVBbnXtJ9i8nhPCXe9HSfZBPpgeOxp+6Tiny50kjl5HXnNS9IWkAGSu31C5wpawVC/4kBohp7uTxrHBkfL+e3WjIj8fKNJnVH367ErDSK2Qnj4vh8dpincdxjf8Evjv+MlP4f4NKtCJoMv6b3N4ugHz0QCOA/9ppKJQigJKrNxQFFxp2ReYOYH5lH9+Xl6kySmJ7UdH8xR+DLzQVuEJGRfr5gtfQvzPHHricnz5EMCsYZDQRsiZ4UZ7tWDmTSVlpX6kyjNFPoofLOeu98C5C6RuX14fOxq14w1nF5naC3tA/9Ppi2xPqFX20+cvrnlczS3hHhwkcehEKgkdn38uwzy7PFzN1t0gnNP5/Yt1iH6BXFXKR/sje9/2F4ICfoodkuLBQi+q9vNQnp1Jp9l+AY6neQo7dTKS8oLncrkLX3C77InFAo5WIlm4yj3DN5UdmVYmsygLytLGr+MgYd7OlNB8VZIS+zB8NEk2z3ZfUV1Qvy+/8rIf+4cWqMNbe8=
  # Source: http://docs.travis-ci.com/user/deployment/heroku/#Deploy-Strategy
  strategy: git
  app:
    master: basimilch
    dev: basimilch-dev
  run:
    - "rake db:migrate"
  on:
    repo: basimilch/basimilch-app
addons:
  code_climate:
    repo_token:
      secure: qC5Z41NwPZz59EvpX5kM+A7r2WTHJzuXTNIloQGTLpP/QI/tOGJgZ8taYxjU/OzjKM9Qi0xXdshjs/oR9PUWptQY6bb4FSFFLGIr2W614kCYoYJrhlrtvcabIUgrXJ2F38rLp1PSfLSnGkAGH+e9qm+IAyGb3kkoLr7NDpqWWTL/r8j7quaBoR2NB62vRNPxUAyl9xdq4OQ8wqGNx9ALDpnGetjdDBzugnoRh/8uXzld0hC+EycpiPrWWgkenmbPVV6JK2EF/G7/fl/tnPzseT8X14oW2y2u4o9QdTMcAgCsHzAka+o8Ty+MYyu7iReeVH1p/6/875gUn7/7yz6Ivum34C/ErgTGNhKXKj3F7yEyrb1mtkttBT/1I463wtZPi/JRBKof7jhP623ZGhYP/6CR0q6gEDT6sspmUekaYAb9covtRS4KDDlzgOOGVWUoS7f7qUetrw9eJz1rNr2Yo3G61sbP8SSMZu5J+2tKk7fESTD/gHHP9CGLrtZgFSmeiyOvyG72brGV57zsH39ozW/zwdkyG3xWLn+R5+bntOn7fj1BzRXoG155I/Ef3jV8Ais+IxjGPkQTlMnhX0kki3hWk2+OiG4HYWiiZwR9KKGX87X4muSximCgBfAd1ZJU6XBnUBXNVQs9Oz/d2A/jhpwWAu9qUal01qKD6GjQz9I=
